### ISSUE TITLE
MK-1862: Only last comments of a Data Access Request can be deleted

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3552] opened 2018-05-24 18:53 UTC
Jira issue originally created by user @kazoompa:

As requested by CaG, once a conversation has began in forms of comments, researcher can only delete the last one of his own, if there are other comments after the server should remove the DELETE permission so only. May be event editing should be removed (?)

**Comment by meek0** [comment] 2018-06-01 16:57
duplicate of mica #3514

**Closed** 2018-06-01 16:57 UTC
Labels: duplicate, new feature
