### ISSUE TITLE
Website url field

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3842] opened 2020-02-06 20:52 UTC
<input type="url">  ?

**Comment by meek0** [comment] 2020-02-11 17:23
Note that the url field is always transform into a true url on the drupal/portal site.

The problem is that an url that does not start with a protocol will be interpreted (by the browser) to be a `relative` url. Thus an url value of `google.ca` on a portal website `https://portal.website.com` will be interpreted as `https://portal.website.com/google.ca`.

The validation would probably need to be stricter. Else need to find a solution.

**Comment by sofiyad** [comment] 2020-02-18 19:51
To review

**Closed** 2020-03-23 15:42 UTC
