### ISSUE TITLE
flexible search result columns

### ISSUE THREAD

**Issue by joerghenkebuero** [obiba/mica2#4039] opened 2020-10-07 08:28 UTC
See the screenshot. I want to remove the type columns from the search result tables.
![grafik](https://user-images.githubusercontent.com/69628891/95306154-4d92b700-0887-11eb-90e3-b170decdea5a.png)
For the variables part, there is an option in the configuration field `searchVariableColumns` in  `templates/libs/settings.ftl`, but there is none for the other two parts `datasets` and `studies`.

Please provide such a parameter that can be adjusted alike `searchVariableColumns`; maybe named similiar such as `searchDatasetColumns` and `searchStudyColumns` or such.

An alternative could be anything that allows me to remove the `type` column from the resulting table.

**Comment by ymarcon** [comment] 2020-10-07 08:32
Duplicate of #4040

**Closed by ymarcon** 2020-10-07 08:32 UTC
